version: '3.9'
services:
  # db:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INIT_DB_ROOT_USERNAME: ${MONGO_USERNAME}
  #     MONGO_INIT_DB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #   ports:
  #    - 27017:27017
  #   # volumes:
  #   #  - mongodb_data_container:/data/db
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db